import "./firebaseinit.js"
import "./ranking.js"
import "./brand.js"
import "./main.js"
import "./productDetail.js"
import "../style/index.css"
import "../style/productDetail.css"
import "../style/brand.css"
import "../style/ranking.css"
import "../style/main.css"

